### ISSUE TITLE
HuggingFace dataset loader does not work

### ISSUE THREAD

**Issue by tingofurro** [wjko2/INQUISITIVE#2]
Hello,
Thanks for creating this very cool dataset!

When trying to run:
```
from datasets import load_dataset
iqg = load_dataset("inquisitive_qg")
```

There's an error as it cannot find the file: https://github.com/wjko2/INQUISITIVE/raw/master/articles.tgz

**Comment by wjko2** [comment]
Unfortunately we cannot publicly release the news articles due to copyright.
Please send me an email for the articles (wjko@outlook.com).
